// Generated by https://quicktype.io

export interface RestaurantDetail {
    restaurantDetails: RestaurantDetailElement[];
}

export interface RestaurantDetailElement {
    restaurantName:        string;
    restaurantDescription: string;
    restaurantImage:       string;
    openingHours:          string;
    contactNumber:         string;
    websiteUrl:            string;
    id:                    number;
}
